name: Frontend Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_ROOT: "http://localhost:4000"
      APP_URL_ROOT: http://localhost:3000
      API_ROOT_URL: http://localhost:4000

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: cd ../backend && npm run dev, npm start
          wait-on: http://localhost:4000, http://localhost:3000
          working-directory: "./frontend"
