name: Frontend Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_ROOT: "http://localhost:4000"
      NODE_ENV: "test"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      APP_URL_ROOT: http://localhost:3000
      API_ROOT_URL: http://localhost:4000
      ROOT_DOMAIN: localhost

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: npm ci

      - name: Setup PostgreSQL
        uses: harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: 11
          postgresql db: test
          postgresql user: test
          postgresql password: test

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm run test:serve
          working-directory: "./frontend"
